<a href="https://colab.research.google.com/github/RevazRevazashvili/TSU-python-labs/blob/main/Lab_10_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [NumPy](https://numpy.org/) Tutorial
**NumPy**-ის მთავარ ობიექტს წარმოადგენს ერთგვაროვანი(ერთი და იმავე ტიპის) მრავალგანზომილებიანი array.

## მოდულის ჩატვირთვა

In [1]:
import numpy as np

### ვერსია
`__version__`

**dunder** - Double Underscore

In [2]:
print(np.__version__)

1.25.2


### საბაზისო

In [30]:
# a = np.array([1,2,3,4,5,6], np.int32)
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [10]:
# ინტეჯერების მასივის შექმნა

np.array((1,2,3), int)

array([1, 2, 3])

In [11]:
# ნამდვილი რიცხვების მასივის შექმნა

np.array((1,2,3), float)

array([1., 2., 3.])

In [17]:
# სტრიქონების მასივის შექმნა

np.array(('1','2','3'), str)

array(['1', '2', '3'], dtype='<U1')

In [18]:
# ინფორმაციის გამოტანა
# np.info(np.array)

#### Inspecting

In [19]:
# განზომილება
a.ndim

1

In [29]:
# ტიპი
a.dtype

dtype('int64')

In [32]:
a.astype('float')

array([1., 2., 3., 4., 5., 6.])

In [34]:
# ელემენტების რაოდენობა
a.size

6

In [36]:
# თითოეული ელემენტის ბიტური ზომა
a.itemsize

8

In [37]:
# ბაიტების საერთო ზომა( ყველა ელემენტის ბაიტების ჯამი)
a.nbytes

48

In [38]:
a.shape

(6,)

In [40]:
c = set([1,2,3])

In [41]:
set_array = np.array(c)

In [42]:
st_array = np.array(['a', 'b'])

In [44]:
''.join(st_array)

'ab'

### მასივის განზომილებები

In [45]:
b = np.array([
    [9.0,8.0,7.0],
    [6.0,5.0,4.0]
])
print(b)
print(type(b))

[[9. 8. 7.]
 [6. 5. 4.]]
<class 'numpy.ndarray'>


In [47]:
# მასივის განზომილება
b.shape

(2, 3)

In [48]:
b.size

6

In [50]:
b.nbytes

48

In [51]:
c = np.array([
    [
        [1,2,3],
        [5,3,4]
    ],
    [
        [1,5,6],
        [5,7,8]]
    ]
)
print(c)
print(type(c))

[[[1 2 3]
  [5 3 4]]

 [[1 5 6]
  [5 7 8]]]
<class 'numpy.ndarray'>


In [52]:
c.shape

(2, 2, 3)

In [53]:
c.size

12

In [54]:
c.nbytes

96

### ზოგიერთი მზა სტრუქტურა

#### zeros()
`zeros()`

In [55]:
# 0-ების მატრიცა ზომიტ(3,4)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### ones()
`ones()`

In [59]:
# 1-ების სამგანზომილებიანი მატრიცა
np.ones([2,2,3], dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [61]:
# 1-ების სამგანზომილებიანი მატრიცა
np.ones((2,3,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

#### identity()
`identity()`

In [ ]:
# ერთეულოვანი მატრიცა
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### full()
`full()`

In [63]:
# ერთი და იმავე მნიშვნელობის მატრიცა
np.full((3), 81)

array([81, 81, 81])

In [64]:
# ერთი და იმავე მნიშვნელობის მატრიცა
np.full((3,4), 81)

array([[81, 81, 81, 81],
       [81, 81, 81, 81],
       [81, 81, 81, 81]])

In [65]:
# ერთი და იმავე მნიშვნელობის მატრიცა
np.full((3,4,5), 81)

array([[[81, 81, 81, 81, 81],
        [81, 81, 81, 81, 81],
        [81, 81, 81, 81, 81],
        [81, 81, 81, 81, 81]],

       [[81, 81, 81, 81, 81],
        [81, 81, 81, 81, 81],
        [81, 81, 81, 81, 81],
        [81, 81, 81, 81, 81]],

       [[81, 81, 81, 81, 81],
        [81, 81, 81, 81, 81],
        [81, 81, 81, 81, 81],
        [81, 81, 81, 81, 81]]])

In [66]:
print(a)
np.full(a.shape, 5)

[1 2 3 4 5 6]


array([5, 5, 5, 5, 5, 5])

#### full_like()
`full_like()`

In [67]:
# გადაცემული პარამეტრის მსგავსი ახალი მატრიცა შევსებული პარამეტრის მნიშვნელობით
print(a)
np.full_like(a, 5)

[1 2 3 4 5 6]


array([5, 5, 5, 5, 5, 5])

In [68]:
s = 'aba'
np.full_like(s, 4)

array('4', dtype='<U3')

#### repeat()
`repeat()`

In [74]:
# მასივის გამეორება
arr = np.array([
    [1,2,3]
])
print(arr.shape)
r1 = np.repeat(arr, 5, axis=0)
print(r1)

(1, 3)
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [82]:
# მასივის გამეორება
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.shape)
r1 = np.repeat(arr, 5, axis=1)
print(r1)

(2, 3)
[[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]
 [4 4 4 4 4 5 5 5 5 5 6 6 6 6 6]]


In [85]:
# მასივების გამეორება
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


#### linspace()
`linspace()`

In [89]:
np.linspace(0,100,11) # წერტილების აღება თანაბარი დაშორებებით

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [90]:
np.linspace(0,100,11)[1:-1]

array([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [91]:
np.linspace(0,100,10,endpoint=False)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [92]:
np.linspace(0,100,10,endpoint=False)[1:]

array([10., 20., 30., 40., 50., 60., 70., 80., 90.])

#### arange()
პითონის `range()` ფუნქციის მსგავსად, **NumPy**-საც აქვს ფუნქცია `arange()`

In [97]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [99]:
np.arange(0,10,3)

array([0, 3, 6, 9])

### Randomization

In [100]:
# შემთხვევითი ათწილადი რიცხვები
np.random.rand(4,2)

array([[0.15330253, 0.6694603 ],
       [0.94289064, 0.83683712],
       [0.47681657, 0.95054415],
       [0.34653164, 0.83223614]])

In [101]:
np.random.rand(4,2)

array([[0.5099031 , 0.32291874],
       [0.71795629, 0.86541751],
       [0.76632797, 0.152279  ],
       [0.92707694, 0.17701153]])

In [104]:
np.random.seed(0)
np.random.rand(4,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [105]:
np.random.seed(0)
np.random.rand(4,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [106]:
# შემთხვევითი მთელი რიცხვები
np.random.seed(0)
np.random.randint(-4,8, size=(5,5))

array([[ 1, -4, -1,  7, -1],
       [ 3,  5, -1,  1, -2],
       [ 0,  3,  2,  4,  4],
       [ 6, -3,  2,  3,  3],
       [ 4, -3,  1,  5,  4]])

### მასივების კოპირება

In [111]:
a = np.array([1,2,3])
b = a.copy()
c = a

print("before:")
print("a", a)
print("b", b)
print("c", c)

b[0] = 100
print("after b:")
print("a", a)
print("b", b)
print("c", c)

c[0] = 10

print("after c:")
print("a", a)
print("b", b)
print("c", c)

before:
a [1 2 3]
b [1 2 3]
c [1 2 3]
after b:
a [1 2 3]
b [100   2   3]
c [1 2 3]
after c:
a [10  2  3]
b [100   2   3]
c [10  2  3]


In [109]:
# a = [1,2,3]
# b = a.copy()
# c = a
# c[0]=4
# a,b,c

([4, 2, 3], [1, 2, 3], [4, 2, 3])

#### .tolist()
`tolist()`

In [112]:
print(c)
type(c.tolist())

[10  2  3]


list

## ელემენტებზე წვდომა და ცვლილება

### წვდომა

In [ ]:
l = [1,2,3,4,5]
l[1:-1]

[2, 3, 4]

In [114]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [115]:
# ელემენტის დაბრუნება ინდექსით [r, c]
a[1, 5]

13

In [116]:
# სტრიქონის დაბრუნება
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [117]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [118]:
# სვეტის დაბრუნება
a[:, 2]

array([ 3, 10])

In [119]:
print(a)
# [startindex:endindex:stepsize]
a[0, 1:-1:2]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([2, 4, 6])

### Changing

In [122]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [123]:
print("before:\n", a)
a[1][5] = 20
print("after:\n", a)

before:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
after:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [125]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [126]:
print("before:\n", a)
a[1,5] = 20
print("after:\n", a)

before:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
after:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
print("before:\n", a)
a[:,3] = 3
print("after:\n", a)

before:
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
after:
 [[ 1  2  3  3  5  6  7]
 [ 8  9 10  3 12 20 14]]


In [129]:
print("before:\n", a)
a[:,2] = [1000,2000]
print("after:\n", a)

before:
 [[   1    2 1000    4    5    6    7]
 [   8    9 2000   11   12   20   14]]
after:
 [[   1    2 1000    4    5    6    7]
 [   8    9 2000   11   12   20   14]]


In [130]:
print("before:\n", a)
a[:,2] = (1000,2000)
print("after:\n", a)

before:
 [[   1    2 1000    4    5    6    7]
 [   8    9 2000   11   12   20   14]]
after:
 [[   1    2 1000    4    5    6    7]
 [   8    9 2000   11   12   20   14]]


*3-d მაგალითი

In [131]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print("shape:", b.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)


In [132]:
# ელემენტის მიღება
b[0,1,1]

4

In [134]:
b[1]

array([[5, 6],
       [7, 8]])

In [135]:
print("before:\n", b)
b[1,1,:]

before:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([7, 8])

In [ ]:
# ჩანაცვლება
print("before:\n", b)
b[:,1,:] = [[9,9],[8,8]]
print("after:\n", b)

before:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
after:
 [[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [ ]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

#### მაგალით
შექმენით 5x5-ზე მატრიცა 1-იანების საზღვრებით, შუა წრეზე 0-ები და ცენტრში 9
```python
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
```

In [139]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### მასივების რეორგანიზაცია

#### .reshape()
`reshape()`

In [140]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print("before")
print(before)
print("shape:", before.shape)

print('after:')
after = before.reshape((4,2))
print(after)
print("shape:", after.shape)

print('after:')
after = before.reshape((2,2,2))
print(after)
print("shape:", after.shape)

before
[[1 2 3 4]
 [5 6 7 8]]
shape: (2, 4)
after:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
shape: (4, 2)
after:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)


In [141]:
print('after:')
after = before.reshape((1,-1))
print(after)
print("shape:", after.shape)

after:
[[1 2 3 4 5 6 7 8]]
shape: (1, 8)


In [151]:
print('after:')
after = before.reshape((-1,2))
print(after)
print("shape:", after.shape)

after:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
shape: (4, 2)


In [148]:
arr = np.arange(0,12)

In [149]:
arr.reshape(5,2)

ValueError: cannot reshape array of size 12 into shape (5,2)

#### .vstack()
`vstack()`

In [155]:
# ვექტორების ერთმანეთზე დალაგება
# აუცილებელია ზომაში თანაბარი იყოს
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
# v3 = np.arange(9,17).reshape(2,4)


np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

#### .hstack()
`hstack()`

In [161]:
# ჰორიზონტული მიდგმა
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [162]:
np.concatenate((h1,h2),axis=1)

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### .resize()
`resize()`

In [166]:
# Changes to new shape, fills new values with 0
a = np.random.randint(0,11, size=(3,3))
print("before:\n", a)
a.resize((2,5))
print("after:\n", a)

before:
 [[0 0 4]
 [5 5 6]
 [8 4 1]]
after:
 [[0 0 4 5 5]
 [6 8 4 1 0]]


#### .ravel()
`ravel()` აბრუნებს გაშლილ მასივს

In [168]:
# მატრიცის გაშლა 1 განზომილებიან მასივად
print(a)
a.ravel()

[[0 0 4 5 5]
 [6 8 4 1 0]]


array([0, 0, 4, 5, 5, 6, 8, 4, 1, 0])

In [169]:
print(a)
a.ravel(order='F')

[[0 0 4 5 5]
 [6 8 4 1 0]]


array([0, 6, 0, 8, 4, 4, 5, 1, 5, 0])

#### .append()
`append()` - მასივის ბოლოში ამატებს ელემენტებს

In [184]:
a = np.random.randint(1, 10, size=(3,4))
b = np.random.randint(-10, 0, size=(3,4))
d = np.random.randint(1,10, size=(3,4))
print(a)
print(b)
c = np.append(a, b)
c

[[8 3 4 2]
 [6 3 1 2]
 [1 7 1 5]]
[[ -2  -6  -7  -7]
 [ -2  -2  -3 -10]
 [ -7  -2  -3  -3]]


array([  8,   3,   4,   2,   6,   3,   1,   2,   1,   7,   1,   5,  -2,
        -6,  -7,  -7,  -2,  -2,  -3, -10,  -7,  -2,  -3,  -3])

In [180]:
print(a)
print(b)
c1 = np.append(a, b, axis=0)
c1

[[9 1 5 7]
 [6 8 9 9]
 [3 9 7 7]]
[[-1 -9 -4 -2]
 [-2 -7 -8 -7]
 [-4 -7 -4 -5]]


array([[ 9,  1,  5,  7],
       [ 6,  8,  9,  9],
       [ 3,  9,  7,  7],
       [-1, -9, -4, -2],
       [-2, -7, -8, -7],
       [-4, -7, -4, -5]])

In [186]:
print(a)
print(b)
c2 = np.append(a, b, axis=1)
c2

[[8 3 4 2]
 [6 3 1 2]
 [1 7 1 5]]
[[ -2  -6  -7  -7]
 [ -2  -2  -3 -10]
 [ -7  -2  -3  -3]]


array([[  8,   3,   4,   2,  -2,  -6,  -7,  -7],
       [  6,   3,   1,   2,  -2,  -2,  -3, -10],
       [  1,   7,   1,   5,  -7,  -2,  -3,  -3]])

#### .insert()
`insert()`

In [187]:
print(a)
a2 = np.insert(a, 1, -5)
a2

[[8 3 4 2]
 [6 3 1 2]
 [1 7 1 5]]


array([ 8, -5,  3,  4,  2,  6,  3,  1,  2,  1,  7,  1,  5])

In [190]:
print(a)
a2_1 = np.insert(a, 1, -5, axis=0)
a2_1

[[8 3 4 2]
 [6 3 1 2]
 [1 7 1 5]]


array([[ 8,  3,  4,  2],
       [-5, -5, -5, -5],
       [ 6,  3,  1,  2],
       [ 1,  7,  1,  5]])

In [192]:
print(a)
a2_2 = np.insert(a, 1, -5, axis=0)
a2_2

[[8 3 4 2]
 [6 3 1 2]
 [1 7 1 5]]


array([[ 8,  3,  4,  2],
       [-5, -5, -5, -5],
       [ 6,  3,  1,  2],
       [ 1,  7,  1,  5]])

#### .delete()
`delete()`

In [193]:
print(b)
b2 = np.delete(b, 0)
b2

[[ -2  -6  -7  -7]
 [ -2  -2  -3 -10]
 [ -7  -2  -3  -3]]


array([ -6,  -7,  -7,  -2,  -2,  -3, -10,  -7,  -2,  -3,  -3])

In [194]:
print(b)
b2_1 = np.delete(b, 1, axis=0)
b2_1

[[ -2  -6  -7  -7]
 [ -2  -2  -3 -10]
 [ -7  -2  -3  -3]]


array([[-2, -6, -7, -7],
       [-7, -2, -3, -3]])

In [195]:
print(b)
b2_2 = np.delete(b, 1, axis=1)
b2_2

[[ -2  -6  -7  -7]
 [ -2  -2  -3 -10]
 [ -7  -2  -3  -3]]


array([[ -2,  -7,  -7],
       [ -2,  -3, -10],
       [ -7,  -3,  -3]])